name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  BASE_URL: '${{ var.BASE_URL }}'
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --no-audit --no-fund

    - name: Build static site
      run: npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H knuth-it.duckdns.org >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      run: |
        scp -i ~/.ssh/id_rsa -P 22 -r dist/* alberto@knuth-it.duckdns.org:/var/www/html/content/
        
    - name: Cleanup SSH
      run: |
        rm -rf ~/.ssh 
